### ISSUE TITLE
KeyError during loading vgg16.npy

### ISSUE THREAD

**Issue by wenouyang** [MarvinTeichmann/KittiBox#42]
Hi, Thank you for sharing the code.

I have been trying to run demo.py. However, architeucture.py gives the following error message, looks like it comes from loading vgg16.npy.  Would you like to see what can be the reason? Thanks.

`2017-08-17 12:02:06,779 INFO Hypes loaded successfully.
2017-08-17 12:02:07,055 INFO Modules loaded successfully. Starting to build tf graph.
npy file loaded
Traceback (most recent call last):
  File "demo.py", line 223, in <module>
    tf.app.run()
  File "/data/dsp_emerging/anaconda/Anaconda27/envs/python27/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "demo.py", line 142, in main
    image=image)
  File "/home/DL-Phase3/KittiBox-master/submodules/TensorVision/tensorvision/core.py", line 137, in build_inference_graph
    logits = modules['arch'].inference(hypes, image, train=False)
  File "/data/dsp_emerging/DL-Phase3/KittiBox/KittiBox_pretrained/model_files/architecture.py", line 29, in inference
    random_init_fc8=True)
  File "/home/DL-Phase3/KittiBox-master/submodules/tensorflowfcn/fcn8_vgg.py", line 74, in build
    self.conv1_1 = self._conv_layer(bgr, "conv1_1")
  File "/home/DL-Phase3/KittiBox-master/submodules/tensorflowfcn/fcn8_vgg.py", line 154, in _conv_layer
    filt = self.get_conv_filter(name)
  File "/home/DL-Phase3/KittiBox-master/submodules/tensorflowfcn/fcn8_vgg.py", line 281, in get_conv_filter
    init = tf.constant_initializer(value=self.data_dict[name][0],dtype=tf.float32)
KeyError: 0
`

**Comment by qmanalex** [comment]
I have the same problem!
When I run demo.py , it shows "ERROR file 'DATA/vgg16.npy' not found. Download it from ftp://mi.eng.cam.ac.u;/pub/mtt2/models/vgg16.npy". I have downloaded the file vgg16.npy , but I can't find which folder I should put vgg16.npy. Please tell me the answer, thanks.

**Comment by MartinQingM** [comment]
You need to create a new folder named DATA, and put vgg16.npy in it.

**Comment by danceL** [comment]
Do i must put vgg16.npy in it ? but i just want run demo.py.

**Comment by ChinmayKalyankar** [comment]
where must i create the DATA folder ??

**Comment by danceL** [comment]
@ChinmayKalyankar you need to create DATA folder in KittiBox
![1521443377 1](https://user-images.githubusercontent.com/26337242/37582414-cbd95446-2b87-11e8-9653-2fa23f2eb242.png)
