### ISSUE TITLE
when run the train.py,it can only run one epoch. why?

### ISSUE THREAD

**Issue by baolinhu** [MarvinTeichmann/KittiBox#54]
`Traceback (most recent call last):
  File "/home/dlwork/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1323, in _do_call
    return fn(*args)
  File "/home/dlwork/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1302, in _run_fn
    status, run_metadata)
  File "/home/dlwork/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: 0-th value returned by pyfunc_0 is uint8, but expects float
	 [[Node: Evaluation/PyFunc = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT32, DT_STRING], Tout=[DT_FLOAT], token="pyfunc_0", _device="/job:localhost/replica:0/task:0/device:CPU:0"](Inputs/Maximum/_147, Evaluation/strided_slice/_365, Evaluation/strided_slice_1/_367, Optimizer/Variable/read, Evaluation/PyFunc/input_4)]]
	 [[Node: Evaluation/PyFunc/_369 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_1186_Evaluation/PyFunc", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 82, in <module>
    tf.app.run()
  File "/home/dlwork/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train.py", line 78, in main
    train.do_training(hypes)
  File "incl/tensorvision/train.py", line 395, in do_training
    run_training(hypes, modules, tv_graph, tv_sess)
  File "incl/tensorvision/train.py", line 264, in run_training
    feed_dict=feed_dict)
  File "/home/dlwork/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/home/dlwork/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/dlwork/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/home/dlwork/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 0-th value returned by pyfunc_0 is uint8, but expects float
	 [[Node: Evaluation/PyFunc = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT32, DT_STRING], Tout=[DT_FLOAT], token="pyfunc_0", _device="/job:localhost/replica:0/task:0/device:CPU:0"](Inputs/Maximum/_147, Evaluation/strided_slice/_365, Evaluation/strided_slice_1/_367, Optimizer/Variable/read, Evaluation/PyFunc/input_4)]]
	 [[Node: Evaluation/PyFunc/_369 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_1186_Evaluation/PyFunc", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

Caused by op 'Evaluation/PyFunc', defined at:
  File "train.py", line 82, in <module>
    tf.app.run()
  File "/home/dlwork/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train.py", line 78, in main
    train.do_training(hypes)
  File "incl/tensorvision/train.py", line 376, in do_training
    tv_graph = core.build_training_graph(hypes, queue, modules)
  File "incl/tensorvision/core.py", line 105, in build_training_graph
    hypes, image, labels, decoded_logits, losses, global_step)
  File "/mnt/fpan/HBL_data/data_set/KITTI/KittiBox/hypes/../decoder/fastBox.py", line 476, in evaluation
    [tf.float32])
  File "/home/dlwork/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/script_ops.py", line 212, in py_func
    input=inp, token=token, Tout=Tout, name=name)
  File "/home/dlwork/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/gen_script_ops.py", line 50, in _py_func
    "PyFunc", input=input, token=token, Tout=Tout, name=name)
  File "/home/dlwork/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/dlwork/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/home/dlwork/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): 0-th value returned by pyfunc_0 is uint8, but expects float
	 [[Node: Evaluation/PyFunc = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT32, DT_STRING], Tout=[DT_FLOAT], token="pyfunc_0", _device="/job:localhost/replica:0/task:0/device:CPU:0"](Inputs/Maximum/_147, Evaluation/strided_slice/_365, Evaluation/strided_slice_1/_367, Optimizer/Variable/read, Evaluation/PyFunc/input_4)]]
	 [[Node: Evaluation/PyFunc/_369 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_1186_Evaluation/PyFunc", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
`

**Comment by andreleoni** [comment]
I'm getting the same problem :/
