### ISSUE TITLE
python demo.py --input image data/demo.png is not working ...

### ISSUE THREAD

**Issue by learner62** [MarvinTeichmann/KittiBox#56]
Your 1. example in Tutorial -> Getting started does not work in my environment but gives:

2018-02-08 20:43:57,633 INFO Starting inference using data/demo.png as input
Traceback (most recent call last):
  File "demo.py", line 219, in <module>
    tf.app.run()
  File "/Users/erkki/tensorflow/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "demo.py", line 175, in main
    min_conf=0.50, tau=hypes['tau'], color_acc=(0, 255, 0))
  File "incl/utils/train_utils.py", line 103, in add_rectangles
    from utils.stitch_wrapper import stitch_rects
ImportError: dynamic module does not define module export function (PyInit_stitch_wrapper)

I'm running your code on macOS High Sierra version 10.13.3 and installed tensorflow and all SW you mentioned according your instructions and instructions by tensorflow. How could this situation be fixed ?

**Comment by apgiorgi** [comment]
Happened to me using a conda environment.

Apparently, during setup `make` is compiling a cython module against Python2 and not Python3, as your environment expects (pip linked to python3?).

Try doing manually step 3 of setup, like:
```
cd submodules/utils
pip install runcython3
makecython3++ stitch_wrapper.pyx "" "stitch_rects.cpp ./hungarian/hungarian.cpp"
```

**Comment by JohnnyD1** [comment]
@apgiorgi manually doing step 3 as you have shown gives a segfault at the line:
`from utils.stitch_wrapper import stitch_rects `
in KittiBox/submodules/utils/train_utils.py

Edit: I do get a warning when running:
```
makecython3++ stitch_wrapper.pyx "" "stitch_rects.cpp ./hungarian/hungarian.cpp"`

`FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: .../KittiBox/submodules/utils/stitch_wrapper.pyx
```

Edit2: Solved this issue by avoiding altogether using makefile. I instead created the following script called KittiBox/incl/utils/setup.py:

```from Cython.Distutils import build_ext
from distutils.core import setup
from distutils.extension import Extension

import os
#os.environ['CC'] = 'g++'
#os.environ['CXX'] = 'g++'

setup(
    name = "stitch_wrapper",
    ext_modules=[
        Extension('stitch_wrapper',
            sources=["stitch_wrapper.pyx", "stitch_rects.cpp","hungarian/hungarian.cpp"],
            language="c++")                                                                                                                                                     
        ],  
    cmdclass = {'build_ext' : build_ext}
    ) 
```
In KittiBox/incl/utils/ I ran the following command:
`python setup.py build_ext --inplace`
And then finally, in KittiBox/submodules/utils/stitch_wrapper.pyx, I replaced:
`from rect import Rect as PyRect`
with
`from incl.utils.rect import Rect as PyRect`
Running python demo.py --input_image data/demo.png now runs all the way through without any error.
